#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
code () { VSCODE_CWD="$PWD" open -n -b "com.microsoft.VSCode" --args $* }
gi () { curl -L -s https://www.gitignore.io/api/$@ ;}

# added by travis gem
[ -f /Users/minhan/.travis/travis.sh ] && source /Users/minhan/.travis/travis.sh

#direnv
eval "$(direnv hook zsh)"